---
# tasks file for server

- name: Update apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Installing apt dependencies
  apt:
    name: "{{item}}"
  with_items:
    - build-essential
    - python-dev
    - libmysqlclient-dev
    - python3-pip

- name: Install server-packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apache2
    - mysql-server
    - php7.0-mysql
    - php7.0
    - libapache2-mod-php7.0
    - php7.0-mcrypt
    - python3-mysqldb
